spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

  h2:
    console:
      enabled: true

  # ✅ EMAIL CONFIGURATION
  mail:
    host: smtp.gmail.com
    port: 587
    username: ganabs0819@gmail.com
    password: jnmh kaht jrrx kaqb

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true